### ISSUE TITLE
[Checklist] Features

### ISSUE THREAD

**Issue by wustep** [wustep/stemee#4]
- [ ] Add students page for administrators to view all students from a given list *
- [ ] Add statistics page for administrators to view statistics from a given list *
- [ ] Add approval features? Maybe.

\* - Authentication of some sort? maybe just a quick password in the main spreadsheet for each list?
